name: Validaci贸n de Compilaci贸n (CI)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Compilar Proyecto
    runs-on: windows-latest

    steps:
    - name: Obtener c贸digo
      uses: actions/checkout@v4

    - name: Configurar MSBuild
      uses: microsoft/setup-msbuild@v1.1

    - name: Configurar NuGet
      uses: NuGet/setup-nuget@v1.2

    - name: Restaurar dependencias
      run: nuget restore X-Wings_Orders.sln

    - name: Descargar instalador de Crystal Reports (EXE)
      shell: powershell
      run: |
        Invoke-WebRequest -Uri "https://github.com/JobHuntersSystems/X-Wings_Orders/releases/download/dependencias-cr/CRforVS13SP28_0-10010309.EXE" -OutFile "CRInstaller.exe"

    - name: Instalar Crystal Reports silenciosamente
      shell: powershell
      run: |
        Start-Process -FilePath "CRInstaller.exe" -ArgumentList "/q" -Wait -NoNewWindow

    - name: Compilar Soluci贸n
      run: msbuild X-Wings_Orders.sln /p:Configuration=Release /p:Platform="Any CPU"

    